### ISSUE TITLE
ARFO breaks BYG source blocks when a block is created with Ore Stone Varients.

### ISSUE THREAD

**Issue by fjdlafjld** [finallion/Artificial_Foliage-FORGE-#1]
So idk what you did in your code. But it causes this. This issue did not exist prior to the downloading of ARFO. The mod dev thinks that you might have messed with the rendering engine. I really do love this mod and I've been using it in custom biomes. But if I keep the mod I can't create custom ores with it. Please fix it. 
![2021-07-10_23 54 05](https://user-images.githubusercontent.com/74016811/125184360-37c96e00-e1da-11eb-8460-86967d0ba209.png)

#Steps to replicate
1. Install BYG, ARFO and Ore Stone varients
2. In a new world search for the OSV blocks. 
3. Place the ores that have a BYG source block. 
4. If done correctly you will see this error with the blocks.

**Comment by finallion** [comment]
Indeed seems to be caused by my mod. I was able to reproduce the error. It has nothing to do with the rendering engine though. I'd nether messed with that. It might be caused by OSV thinking some of my blocks are part of BYG and therefore cant find the correct texture. I'll look into it and see what I can do!

**Comment by finallion** [comment]
![2021-07-11_14 57 23](https://user-images.githubusercontent.com/74151350/125195999-71d95500-e258-11eb-97b1-0b8a0b4fcc69.png)

Seems indeed to be the case. The naming of some of my blocks causes OSV to look in the wrong place for its textures. I fixed that and it looks like it works. I'll make some adjustments and upload a new version soon.

**Comment by fjdlafjld** [comment]
Nice. I'll be testing it on Monday. I'm hoping it works
