### ISSUE TITLE
The Mod will not load in forge 1.17.1

### ISSUE THREAD

**Issue by ghost** [finallion/Artificial_Foliage-FORGE-#2]
I am using Artificial Foliage it is not loading
PLZ FIX IT I want to use this wonderful mod
Also plz add stuff from bop 1.17.1

LOGS-
[debug.log](https://github.com/finallion/Artificial_Foliage-FORGE-/files/7064553/debug.log)
[latest.log](https://github.com/finallion/Artificial_Foliage-FORGE-/files/7064554/latest.log)

Mod Version: Artificial_Foliage_1.0_(FORGE)_for_1.17.1.jar
Game Version: Minecraft-1.17.1
Modloader: Forge
Forge Version: Forge-1.17.1-37.0.44

**Comment by finallion** [comment]
Hey! Forge changed the tool logic in 37.0.31. The error should not occur when using a forge version before 37.0.31. I'm working on an update to match the current version.

**Comment by ghost** [comment]
TY
